/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.ui;

import com.google.inject.Injector;
import hu.bme.aut.menetrend.ui.internal.MenetrendActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MenetrendExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MenetrendActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MenetrendActivator.getInstance().getInjector(MenetrendActivator.HU_BME_AUT_MENETREND_MENETREND);
	}
	
}
