/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MenetrendAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hu/bme/aut/menetrend/parser/antlr/internal/InternalMenetrend.tokens");
	}
}
