/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.parser.antlr;

import com.google.inject.Inject;
import hu.bme.aut.menetrend.parser.antlr.internal.InternalMenetrendParser;
import hu.bme.aut.menetrend.services.MenetrendGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MenetrendParser extends AbstractAntlrParser {

	@Inject
	private MenetrendGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMenetrendParser createParser(XtextTokenStream stream) {
		return new InternalMenetrendParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MenetrendGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MenetrendGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
