/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Absolute Schedule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.AbsoluteSchedule#getDaytype <em>Daytype</em>}</li>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.AbsoluteSchedule#getDepartures <em>Departures</em>}</li>
 * </ul>
 *
 * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getAbsoluteSchedule()
 * @model
 * @generated
 */
public interface AbsoluteSchedule extends SchedulePart
{
  /**
   * Returns the value of the '<em><b>Daytype</b></em>' attribute.
   * The literals are from the enumeration {@link hu.bme.aut.menetrend.menetrend.DayType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Daytype</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Daytype</em>' attribute.
   * @see hu.bme.aut.menetrend.menetrend.DayType
   * @see #setDaytype(DayType)
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getAbsoluteSchedule_Daytype()
   * @model
   * @generated
   */
  DayType getDaytype();

  /**
   * Sets the value of the '{@link hu.bme.aut.menetrend.menetrend.AbsoluteSchedule#getDaytype <em>Daytype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Daytype</em>' attribute.
   * @see hu.bme.aut.menetrend.menetrend.DayType
   * @see #getDaytype()
   * @generated
   */
  void setDaytype(DayType value);

  /**
   * Returns the value of the '<em><b>Departures</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.aut.menetrend.menetrend.Departure}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Departures</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Departures</em>' containment reference list.
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getAbsoluteSchedule_Departures()
   * @model containment="true"
   * @generated
   */
  EList<Departure> getDepartures();

} // AbsoluteSchedule
