/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Day Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getDayType()
 * @model
 * @generated
 */
public enum DayType implements Enumerator
{
  /**
   * The '<em><b>WEEKDAYS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEEKDAYS_VALUE
   * @generated
   * @ordered
   */
  WEEKDAYS(0, "WEEKDAYS", "weekdays"),

  /**
   * The '<em><b>WEEKENDS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEEKENDS_VALUE
   * @generated
   * @ordered
   */
  WEEKENDS(1, "WEEKENDS", "weekends"),

  /**
   * The '<em><b>MONDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MONDAY_VALUE
   * @generated
   * @ordered
   */
  MONDAY(2, "MONDAY", "monday"),

  /**
   * The '<em><b>TUESDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TUESDAY_VALUE
   * @generated
   * @ordered
   */
  TUESDAY(3, "TUESDAY", "tuesday"),

  /**
   * The '<em><b>WEDNESDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEDNESDAY_VALUE
   * @generated
   * @ordered
   */
  WEDNESDAY(4, "WEDNESDAY", "wednesday"),

  /**
   * The '<em><b>THURSDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THURSDAY_VALUE
   * @generated
   * @ordered
   */
  THURSDAY(5, "THURSDAY", "thursday"),

  /**
   * The '<em><b>FRIDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FRIDAY_VALUE
   * @generated
   * @ordered
   */
  FRIDAY(6, "FRIDAY", "friday"),

  /**
   * The '<em><b>SATURDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SATURDAY_VALUE
   * @generated
   * @ordered
   */
  SATURDAY(7, "SATURDAY", "saturday"),

  /**
   * The '<em><b>SUNDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SUNDAY_VALUE
   * @generated
   * @ordered
   */
  SUNDAY(8, "SUNDAY", "sunday");

  /**
   * The '<em><b>WEEKDAYS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WEEKDAYS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEEKDAYS
   * @model literal="weekdays"
   * @generated
   * @ordered
   */
  public static final int WEEKDAYS_VALUE = 0;

  /**
   * The '<em><b>WEEKENDS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WEEKENDS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEEKENDS
   * @model literal="weekends"
   * @generated
   * @ordered
   */
  public static final int WEEKENDS_VALUE = 1;

  /**
   * The '<em><b>MONDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MONDAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MONDAY
   * @model literal="monday"
   * @generated
   * @ordered
   */
  public static final int MONDAY_VALUE = 2;

  /**
   * The '<em><b>TUESDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TUESDAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TUESDAY
   * @model literal="tuesday"
   * @generated
   * @ordered
   */
  public static final int TUESDAY_VALUE = 3;

  /**
   * The '<em><b>WEDNESDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WEDNESDAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEDNESDAY
   * @model literal="wednesday"
   * @generated
   * @ordered
   */
  public static final int WEDNESDAY_VALUE = 4;

  /**
   * The '<em><b>THURSDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>THURSDAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #THURSDAY
   * @model literal="thursday"
   * @generated
   * @ordered
   */
  public static final int THURSDAY_VALUE = 5;

  /**
   * The '<em><b>FRIDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FRIDAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FRIDAY
   * @model literal="friday"
   * @generated
   * @ordered
   */
  public static final int FRIDAY_VALUE = 6;

  /**
   * The '<em><b>SATURDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SATURDAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SATURDAY
   * @model literal="saturday"
   * @generated
   * @ordered
   */
  public static final int SATURDAY_VALUE = 7;

  /**
   * The '<em><b>SUNDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SUNDAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SUNDAY
   * @model literal="sunday"
   * @generated
   * @ordered
   */
  public static final int SUNDAY_VALUE = 8;

  /**
   * An array of all the '<em><b>Day Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final DayType[] VALUES_ARRAY =
    new DayType[]
    {
      WEEKDAYS,
      WEEKENDS,
      MONDAY,
      TUESDAY,
      WEDNESDAY,
      THURSDAY,
      FRIDAY,
      SATURDAY,
      SUNDAY,
    };

  /**
   * A public read-only list of all the '<em><b>Day Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<DayType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Day Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DayType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DayType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Day Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DayType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DayType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Day Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DayType get(int value)
  {
    switch (value)
    {
      case WEEKDAYS_VALUE: return WEEKDAYS;
      case WEEKENDS_VALUE: return WEEKENDS;
      case MONDAY_VALUE: return MONDAY;
      case TUESDAY_VALUE: return TUESDAY;
      case WEDNESDAY_VALUE: return WEDNESDAY;
      case THURSDAY_VALUE: return THURSDAY;
      case FRIDAY_VALUE: return FRIDAY;
      case SATURDAY_VALUE: return SATURDAY;
      case SUNDAY_VALUE: return SUNDAY;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private DayType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //DayType
