/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see hu.bme.aut.menetrend.menetrend.MenetrendFactory
 * @model kind="package"
 * @generated
 */
public interface MenetrendPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "menetrend";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.bme.hu/aut/menetrend/Menetrend";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "menetrend";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MenetrendPackage eINSTANCE = hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl.init();

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.ModelImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Stops</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STOPS = 0;

  /**
   * The feature id for the '<em><b>Schedules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SCHEDULES = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.ScheduleImpl <em>Schedule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.ScheduleImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getSchedule()
   * @generated
   */
  int SCHEDULE = 1;

  /**
   * The feature id for the '<em><b>Line Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__LINE_NUMBER = 0;

  /**
   * The feature id for the '<em><b>Schedule Parts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__SCHEDULE_PARTS = 1;

  /**
   * The number of structural features of the '<em>Schedule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.LineNumberImpl <em>Line Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.LineNumberImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getLineNumber()
   * @generated
   */
  int LINE_NUMBER = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_NUMBER__TYPE = 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_NUMBER__NUMBER = 1;

  /**
   * The number of structural features of the '<em>Line Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_NUMBER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.SchedulePartImpl <em>Schedule Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.SchedulePartImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getSchedulePart()
   * @generated
   */
  int SCHEDULE_PART = 3;

  /**
   * The number of structural features of the '<em>Schedule Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE_PART_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.RelativeScheduleImpl <em>Relative Schedule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.RelativeScheduleImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getRelativeSchedule()
   * @generated
   */
  int RELATIVE_SCHEDULE = 4;

  /**
   * The feature id for the '<em><b>Start</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_SCHEDULE__START = SCHEDULE_PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Targets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_SCHEDULE__TARGETS = SCHEDULE_PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Relative Schedule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_SCHEDULE_FEATURE_COUNT = SCHEDULE_PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.RelativeTargetImpl <em>Relative Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.RelativeTargetImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getRelativeTarget()
   * @generated
   */
  int RELATIVE_TARGET = 5;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_TARGET__LENGTH = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_TARGET__TARGET = 1;

  /**
   * The number of structural features of the '<em>Relative Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIVE_TARGET_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.AbsoluteScheduleImpl <em>Absolute Schedule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.AbsoluteScheduleImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getAbsoluteSchedule()
   * @generated
   */
  int ABSOLUTE_SCHEDULE = 6;

  /**
   * The feature id for the '<em><b>Daytype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSOLUTE_SCHEDULE__DAYTYPE = SCHEDULE_PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Departures</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSOLUTE_SCHEDULE__DEPARTURES = SCHEDULE_PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Absolute Schedule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSOLUTE_SCHEDULE_FEATURE_COUNT = SCHEDULE_PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.DepartureImpl <em>Departure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.DepartureImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getDeparture()
   * @generated
   */
  int DEPARTURE = 7;

  /**
   * The feature id for the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPARTURE__FROM = 0;

  /**
   * The number of structural features of the '<em>Departure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPARTURE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.SimpleTimeFormatImpl <em>Simple Time Format</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.SimpleTimeFormatImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getSimpleTimeFormat()
   * @generated
   */
  int SIMPLE_TIME_FORMAT = 8;

  /**
   * The feature id for the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_TIME_FORMAT__FROM = DEPARTURE__FROM;

  /**
   * The number of structural features of the '<em>Simple Time Format</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_TIME_FORMAT_FEATURE_COUNT = DEPARTURE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.ComplexTimeMiddleImpl <em>Complex Time Middle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.ComplexTimeMiddleImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getComplexTimeMiddle()
   * @generated
   */
  int COMPLEX_TIME_MIDDLE = 9;

  /**
   * The feature id for the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TIME_MIDDLE__FROM = DEPARTURE__FROM;

  /**
   * The feature id for the '<em><b>Until</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TIME_MIDDLE__UNTIL = DEPARTURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TIME_MIDDLE__FREQUENCY = DEPARTURE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Complex Time Middle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TIME_MIDDLE_FEATURE_COUNT = DEPARTURE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.ComplexTimeEndImpl <em>Complex Time End</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.ComplexTimeEndImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getComplexTimeEnd()
   * @generated
   */
  int COMPLEX_TIME_END = 10;

  /**
   * The feature id for the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TIME_END__FROM = DEPARTURE__FROM;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TIME_END__FREQUENCY = DEPARTURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Until</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TIME_END__UNTIL = DEPARTURE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Complex Time End</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TIME_END_FEATURE_COUNT = DEPARTURE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.impl.StopImpl <em>Stop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.impl.StopImpl
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getStop()
   * @generated
   */
  int STOP = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP__NAME = 0;

  /**
   * The number of structural features of the '<em>Stop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.TransportType <em>Transport Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.TransportType
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getTransportType()
   * @generated
   */
  int TRANSPORT_TYPE = 12;

  /**
   * The meta object id for the '{@link hu.bme.aut.menetrend.menetrend.DayType <em>Day Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.aut.menetrend.menetrend.DayType
   * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getDayType()
   * @generated
   */
  int DAY_TYPE = 13;


  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.aut.menetrend.menetrend.Model#getStops <em>Stops</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stops</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Model#getStops()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Stops();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.aut.menetrend.menetrend.Model#getSchedules <em>Schedules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Schedules</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Model#getSchedules()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Schedules();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.Schedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schedule</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Schedule
   * @generated
   */
  EClass getSchedule();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.aut.menetrend.menetrend.Schedule#getLineNumber <em>Line Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Number</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Schedule#getLineNumber()
   * @see #getSchedule()
   * @generated
   */
  EReference getSchedule_LineNumber();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.aut.menetrend.menetrend.Schedule#getScheduleParts <em>Schedule Parts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Schedule Parts</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Schedule#getScheduleParts()
   * @see #getSchedule()
   * @generated
   */
  EReference getSchedule_ScheduleParts();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.LineNumber <em>Line Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line Number</em>'.
   * @see hu.bme.aut.menetrend.menetrend.LineNumber
   * @generated
   */
  EClass getLineNumber();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.LineNumber#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see hu.bme.aut.menetrend.menetrend.LineNumber#getType()
   * @see #getLineNumber()
   * @generated
   */
  EAttribute getLineNumber_Type();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.LineNumber#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see hu.bme.aut.menetrend.menetrend.LineNumber#getNumber()
   * @see #getLineNumber()
   * @generated
   */
  EAttribute getLineNumber_Number();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.SchedulePart <em>Schedule Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schedule Part</em>'.
   * @see hu.bme.aut.menetrend.menetrend.SchedulePart
   * @generated
   */
  EClass getSchedulePart();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.RelativeSchedule <em>Relative Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relative Schedule</em>'.
   * @see hu.bme.aut.menetrend.menetrend.RelativeSchedule
   * @generated
   */
  EClass getRelativeSchedule();

  /**
   * Returns the meta object for the reference '{@link hu.bme.aut.menetrend.menetrend.RelativeSchedule#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Start</em>'.
   * @see hu.bme.aut.menetrend.menetrend.RelativeSchedule#getStart()
   * @see #getRelativeSchedule()
   * @generated
   */
  EReference getRelativeSchedule_Start();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.aut.menetrend.menetrend.RelativeSchedule#getTargets <em>Targets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Targets</em>'.
   * @see hu.bme.aut.menetrend.menetrend.RelativeSchedule#getTargets()
   * @see #getRelativeSchedule()
   * @generated
   */
  EReference getRelativeSchedule_Targets();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.RelativeTarget <em>Relative Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relative Target</em>'.
   * @see hu.bme.aut.menetrend.menetrend.RelativeTarget
   * @generated
   */
  EClass getRelativeTarget();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.RelativeTarget#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see hu.bme.aut.menetrend.menetrend.RelativeTarget#getLength()
   * @see #getRelativeTarget()
   * @generated
   */
  EAttribute getRelativeTarget_Length();

  /**
   * Returns the meta object for the reference '{@link hu.bme.aut.menetrend.menetrend.RelativeTarget#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see hu.bme.aut.menetrend.menetrend.RelativeTarget#getTarget()
   * @see #getRelativeTarget()
   * @generated
   */
  EReference getRelativeTarget_Target();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.AbsoluteSchedule <em>Absolute Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Absolute Schedule</em>'.
   * @see hu.bme.aut.menetrend.menetrend.AbsoluteSchedule
   * @generated
   */
  EClass getAbsoluteSchedule();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.AbsoluteSchedule#getDaytype <em>Daytype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Daytype</em>'.
   * @see hu.bme.aut.menetrend.menetrend.AbsoluteSchedule#getDaytype()
   * @see #getAbsoluteSchedule()
   * @generated
   */
  EAttribute getAbsoluteSchedule_Daytype();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.aut.menetrend.menetrend.AbsoluteSchedule#getDepartures <em>Departures</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Departures</em>'.
   * @see hu.bme.aut.menetrend.menetrend.AbsoluteSchedule#getDepartures()
   * @see #getAbsoluteSchedule()
   * @generated
   */
  EReference getAbsoluteSchedule_Departures();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.Departure <em>Departure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Departure</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Departure
   * @generated
   */
  EClass getDeparture();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.Departure#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Departure#getFrom()
   * @see #getDeparture()
   * @generated
   */
  EAttribute getDeparture_From();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.SimpleTimeFormat <em>Simple Time Format</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Time Format</em>'.
   * @see hu.bme.aut.menetrend.menetrend.SimpleTimeFormat
   * @generated
   */
  EClass getSimpleTimeFormat();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.ComplexTimeMiddle <em>Complex Time Middle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Time Middle</em>'.
   * @see hu.bme.aut.menetrend.menetrend.ComplexTimeMiddle
   * @generated
   */
  EClass getComplexTimeMiddle();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.ComplexTimeMiddle#getUntil <em>Until</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Until</em>'.
   * @see hu.bme.aut.menetrend.menetrend.ComplexTimeMiddle#getUntil()
   * @see #getComplexTimeMiddle()
   * @generated
   */
  EAttribute getComplexTimeMiddle_Until();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.ComplexTimeMiddle#getFrequency <em>Frequency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Frequency</em>'.
   * @see hu.bme.aut.menetrend.menetrend.ComplexTimeMiddle#getFrequency()
   * @see #getComplexTimeMiddle()
   * @generated
   */
  EAttribute getComplexTimeMiddle_Frequency();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.ComplexTimeEnd <em>Complex Time End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Time End</em>'.
   * @see hu.bme.aut.menetrend.menetrend.ComplexTimeEnd
   * @generated
   */
  EClass getComplexTimeEnd();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.ComplexTimeEnd#getFrequency <em>Frequency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Frequency</em>'.
   * @see hu.bme.aut.menetrend.menetrend.ComplexTimeEnd#getFrequency()
   * @see #getComplexTimeEnd()
   * @generated
   */
  EAttribute getComplexTimeEnd_Frequency();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.ComplexTimeEnd#getUntil <em>Until</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Until</em>'.
   * @see hu.bme.aut.menetrend.menetrend.ComplexTimeEnd#getUntil()
   * @see #getComplexTimeEnd()
   * @generated
   */
  EAttribute getComplexTimeEnd_Until();

  /**
   * Returns the meta object for class '{@link hu.bme.aut.menetrend.menetrend.Stop <em>Stop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stop</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Stop
   * @generated
   */
  EClass getStop();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.aut.menetrend.menetrend.Stop#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.aut.menetrend.menetrend.Stop#getName()
   * @see #getStop()
   * @generated
   */
  EAttribute getStop_Name();

  /**
   * Returns the meta object for enum '{@link hu.bme.aut.menetrend.menetrend.TransportType <em>Transport Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Transport Type</em>'.
   * @see hu.bme.aut.menetrend.menetrend.TransportType
   * @generated
   */
  EEnum getTransportType();

  /**
   * Returns the meta object for enum '{@link hu.bme.aut.menetrend.menetrend.DayType <em>Day Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Day Type</em>'.
   * @see hu.bme.aut.menetrend.menetrend.DayType
   * @generated
   */
  EEnum getDayType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MenetrendFactory getMenetrendFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.ModelImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Stops</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STOPS = eINSTANCE.getModel_Stops();

    /**
     * The meta object literal for the '<em><b>Schedules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SCHEDULES = eINSTANCE.getModel_Schedules();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.ScheduleImpl <em>Schedule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.ScheduleImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getSchedule()
     * @generated
     */
    EClass SCHEDULE = eINSTANCE.getSchedule();

    /**
     * The meta object literal for the '<em><b>Line Number</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULE__LINE_NUMBER = eINSTANCE.getSchedule_LineNumber();

    /**
     * The meta object literal for the '<em><b>Schedule Parts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULE__SCHEDULE_PARTS = eINSTANCE.getSchedule_ScheduleParts();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.LineNumberImpl <em>Line Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.LineNumberImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getLineNumber()
     * @generated
     */
    EClass LINE_NUMBER = eINSTANCE.getLineNumber();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE_NUMBER__TYPE = eINSTANCE.getLineNumber_Type();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE_NUMBER__NUMBER = eINSTANCE.getLineNumber_Number();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.SchedulePartImpl <em>Schedule Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.SchedulePartImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getSchedulePart()
     * @generated
     */
    EClass SCHEDULE_PART = eINSTANCE.getSchedulePart();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.RelativeScheduleImpl <em>Relative Schedule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.RelativeScheduleImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getRelativeSchedule()
     * @generated
     */
    EClass RELATIVE_SCHEDULE = eINSTANCE.getRelativeSchedule();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIVE_SCHEDULE__START = eINSTANCE.getRelativeSchedule_Start();

    /**
     * The meta object literal for the '<em><b>Targets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIVE_SCHEDULE__TARGETS = eINSTANCE.getRelativeSchedule_Targets();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.RelativeTargetImpl <em>Relative Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.RelativeTargetImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getRelativeTarget()
     * @generated
     */
    EClass RELATIVE_TARGET = eINSTANCE.getRelativeTarget();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIVE_TARGET__LENGTH = eINSTANCE.getRelativeTarget_Length();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIVE_TARGET__TARGET = eINSTANCE.getRelativeTarget_Target();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.AbsoluteScheduleImpl <em>Absolute Schedule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.AbsoluteScheduleImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getAbsoluteSchedule()
     * @generated
     */
    EClass ABSOLUTE_SCHEDULE = eINSTANCE.getAbsoluteSchedule();

    /**
     * The meta object literal for the '<em><b>Daytype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSOLUTE_SCHEDULE__DAYTYPE = eINSTANCE.getAbsoluteSchedule_Daytype();

    /**
     * The meta object literal for the '<em><b>Departures</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSOLUTE_SCHEDULE__DEPARTURES = eINSTANCE.getAbsoluteSchedule_Departures();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.DepartureImpl <em>Departure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.DepartureImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getDeparture()
     * @generated
     */
    EClass DEPARTURE = eINSTANCE.getDeparture();

    /**
     * The meta object literal for the '<em><b>From</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPARTURE__FROM = eINSTANCE.getDeparture_From();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.SimpleTimeFormatImpl <em>Simple Time Format</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.SimpleTimeFormatImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getSimpleTimeFormat()
     * @generated
     */
    EClass SIMPLE_TIME_FORMAT = eINSTANCE.getSimpleTimeFormat();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.ComplexTimeMiddleImpl <em>Complex Time Middle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.ComplexTimeMiddleImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getComplexTimeMiddle()
     * @generated
     */
    EClass COMPLEX_TIME_MIDDLE = eINSTANCE.getComplexTimeMiddle();

    /**
     * The meta object literal for the '<em><b>Until</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_TIME_MIDDLE__UNTIL = eINSTANCE.getComplexTimeMiddle_Until();

    /**
     * The meta object literal for the '<em><b>Frequency</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_TIME_MIDDLE__FREQUENCY = eINSTANCE.getComplexTimeMiddle_Frequency();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.ComplexTimeEndImpl <em>Complex Time End</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.ComplexTimeEndImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getComplexTimeEnd()
     * @generated
     */
    EClass COMPLEX_TIME_END = eINSTANCE.getComplexTimeEnd();

    /**
     * The meta object literal for the '<em><b>Frequency</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_TIME_END__FREQUENCY = eINSTANCE.getComplexTimeEnd_Frequency();

    /**
     * The meta object literal for the '<em><b>Until</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_TIME_END__UNTIL = eINSTANCE.getComplexTimeEnd_Until();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.impl.StopImpl <em>Stop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.impl.StopImpl
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getStop()
     * @generated
     */
    EClass STOP = eINSTANCE.getStop();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOP__NAME = eINSTANCE.getStop_Name();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.TransportType <em>Transport Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.TransportType
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getTransportType()
     * @generated
     */
    EEnum TRANSPORT_TYPE = eINSTANCE.getTransportType();

    /**
     * The meta object literal for the '{@link hu.bme.aut.menetrend.menetrend.DayType <em>Day Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.aut.menetrend.menetrend.DayType
     * @see hu.bme.aut.menetrend.menetrend.impl.MenetrendPackageImpl#getDayType()
     * @generated
     */
    EEnum DAY_TYPE = eINSTANCE.getDayType();

  }

} //MenetrendPackage
