/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.Model#getStops <em>Stops</em>}</li>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.Model#getSchedules <em>Schedules</em>}</li>
 * </ul>
 *
 * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Stops</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.aut.menetrend.menetrend.Stop}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stops</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stops</em>' containment reference list.
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getModel_Stops()
   * @model containment="true"
   * @generated
   */
  EList<Stop> getStops();

  /**
   * Returns the value of the '<em><b>Schedules</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.aut.menetrend.menetrend.Schedule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Schedules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedules</em>' containment reference list.
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getModel_Schedules()
   * @model containment="true"
   * @generated
   */
  EList<Schedule> getSchedules();

} // Model
