/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relative Schedule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.RelativeSchedule#getStart <em>Start</em>}</li>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.RelativeSchedule#getTargets <em>Targets</em>}</li>
 * </ul>
 *
 * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getRelativeSchedule()
 * @model
 * @generated
 */
public interface RelativeSchedule extends SchedulePart
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' reference.
   * @see #setStart(Stop)
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getRelativeSchedule_Start()
   * @model
   * @generated
   */
  Stop getStart();

  /**
   * Sets the value of the '{@link hu.bme.aut.menetrend.menetrend.RelativeSchedule#getStart <em>Start</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' reference.
   * @see #getStart()
   * @generated
   */
  void setStart(Stop value);

  /**
   * Returns the value of the '<em><b>Targets</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.aut.menetrend.menetrend.RelativeTarget}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Targets</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Targets</em>' containment reference list.
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getRelativeSchedule_Targets()
   * @model containment="true"
   * @generated
   */
  EList<RelativeTarget> getTargets();

} // RelativeSchedule
