/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relative Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.RelativeTarget#getLength <em>Length</em>}</li>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.RelativeTarget#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getRelativeTarget()
 * @model
 * @generated
 */
public interface RelativeTarget extends EObject
{
  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Length</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getRelativeTarget_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link hu.bme.aut.menetrend.menetrend.RelativeTarget#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Stop)
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getRelativeTarget_Target()
   * @model
   * @generated
   */
  Stop getTarget();

  /**
   * Sets the value of the '{@link hu.bme.aut.menetrend.menetrend.RelativeTarget#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Stop value);

} // RelativeTarget
