/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schedule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.Schedule#getLineNumber <em>Line Number</em>}</li>
 *   <li>{@link hu.bme.aut.menetrend.menetrend.Schedule#getScheduleParts <em>Schedule Parts</em>}</li>
 * </ul>
 *
 * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getSchedule()
 * @model
 * @generated
 */
public interface Schedule extends EObject
{
  /**
   * Returns the value of the '<em><b>Line Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Line Number</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line Number</em>' containment reference.
   * @see #setLineNumber(LineNumber)
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getSchedule_LineNumber()
   * @model containment="true"
   * @generated
   */
  LineNumber getLineNumber();

  /**
   * Sets the value of the '{@link hu.bme.aut.menetrend.menetrend.Schedule#getLineNumber <em>Line Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Line Number</em>' containment reference.
   * @see #getLineNumber()
   * @generated
   */
  void setLineNumber(LineNumber value);

  /**
   * Returns the value of the '<em><b>Schedule Parts</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.aut.menetrend.menetrend.SchedulePart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Schedule Parts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedule Parts</em>' containment reference list.
   * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getSchedule_ScheduleParts()
   * @model containment="true"
   * @generated
   */
  EList<SchedulePart> getScheduleParts();

} // Schedule
