/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schedule Part</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getSchedulePart()
 * @model
 * @generated
 */
public interface SchedulePart extends EObject
{
} // SchedulePart
