/**
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.menetrend;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Time Format</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.aut.menetrend.menetrend.MenetrendPackage#getSimpleTimeFormat()
 * @model
 * @generated
 */
public interface SimpleTimeFormat extends Departure
{
} // SimpleTimeFormat
