/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MenetrendStandaloneSetup extends MenetrendStandaloneSetupGenerated {

	def static void doSetup() {
		new MenetrendStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
