/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MenetrendRuntimeModule extends AbstractMenetrendRuntimeModule {
}
