/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMenetrendScopeProvider extends DelegatingScopeProvider {
}
