/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.ui.tests;

import com.google.inject.Injector;
import hu.bme.aut.menetrend.ui.internal.MenetrendActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class MenetrendUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MenetrendActivator.getInstance().getInjector("hu.bme.aut.menetrend.Menetrend");
	}

}
