/*
 * generated by Xtext 2.10.0
 */
package hu.bme.aut.menetrend.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMenetrendValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(hu.bme.aut.menetrend.menetrend.MenetrendPackage.eINSTANCE);
		return result;
	}
	
}
